### ISSUE TITLE
running node dist/index.js --drugshortage

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/ts4cpp#2]
running `node dist/index.js --drugshortage` results in
```
Running Drugshortage
(node:1073) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process! spawn /home/zeno/.software/ts4cpp/node_modules/puppeteer/.local-chromium/linux-818858/chrome-linux/chrome ENOENT


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/home/zeno/.software/ts4cpp/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:193:20)
    at ChildProcess.<anonymous> (/home/zeno/.software/ts4cpp/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:185:85)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:12)
    at onErrorNT (internal/child_process.js:468:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:1073) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1073) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by zdavatz** [comment]
Install `v14.15.0`
