### ISSUE TITLE
Unexpected xml node in parseClose: filters

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/ts4cpp#9]
1. I am running the following commands:
```
node dist/index.js --drugshortage
node dist/index.js --chargenrueckrufe
```
results in
2.
```
Error during reading packages xlsx
Error: Unexpected xml node in parseClose: filters
    at AutoFilterXform.parseClose (/home/zdavatz/software/ts4cpp/node_modules/exceljs/lib/xlsx/xform/table/auto-filter-xform.js:76:15)
    at TableXform.parseClose (/home/zdavatz/software/ts4cpp/node_modules/exceljs/lib/xlsx/xform/table/table-xform.js:90:24)
    at TableXform.parse (/home/zdavatz/software/ts4cpp/node_modules/exceljs/lib/xlsx/xform/base-xform.js:67:21)
```

**Comment by zdavatz** [comment]
The output seems to work well. Closing.

**Comment by zdavatz** [comment]
related issue: https://github.com/exceljs/exceljs/issues/1633
